sdk:
# Only "pubspec" because the test uses the platform dill from the SDK, and it
# needs to be the same version.
- pubspec

stages:
- analyze_and_format:
  - analyze: --fatal-infos .
  - format:
    sdk:
    - dev
- unit_test:
  - test: --test-randomize-ordering-seed=random
    os:
    - linux
    - windows
