#!/bin/bash --
#
# Updates ref to SDK packages in pubspec.yaml.

REF=$1

if echo $REF | grep -Eqv '^[a-z0-9][a-z0-9-]*$'; then
  echo "Doesn't look like a git ref? $REF"
  echo "Usage: tool/set_sdk_version <git ref>"
  exit 1
fi

sed -i -e "s#^      ref: .*#      ref: $REF#" pubspec.yaml
