sdk:
- pubspec
- dev

stages:
- analyze_and_format:
  - analyze: --fatal-infos .
  - format:
    sdk:
    - dev
- unit_test:
  - test: --test-randomize-ordering-seed=random && dart -Ddebug_json_buffer=true test --test-randomize-ordering-seed=random -c source
    os:
    - linux
    - windows
